# Auto-generated from Entropia Nexus amplifiers.json.
# This file is hardcoded and does not call the internet.
#
# Values:
#   decay       - item decay as exported by Entropia Nexus
#   ammo_burn   - ammo burn as exported by Entropia Nexus
#   skill_bonus - amplifier Skill Gain effect strength; None if missing

AMPLIFIERS = {'ArMatrix B-Amplifier 10P (L)': {'decay': 0.16, 'ammo_burn': 210, 'skill_bonus': None},
 'ArMatrix B-Amplifier 13P (L)': {'decay': 0.208, 'ammo_burn': 273, 'skill_bonus': None},
 'ArMatrix B-Amplifier 17P (L)': {'decay': 0.272, 'ammo_burn': 357, 'skill_bonus': None},
 'ArMatrix B-Amplifier 20P (L)': {'decay': 0.32, 'ammo_burn': 420, 'skill_bonus': None},
 'ArMatrix B-Amplifier 23P (L)': {'decay': 0.368, 'ammo_burn': 483, 'skill_bonus': None},
 'ArMatrix B-Amplifier 25P (L)': {'decay': 0.4, 'ammo_burn': 525, 'skill_bonus': None},
 'ArMatrix B-Amplifier 28P (L)': {'decay': 0.448, 'ammo_burn': 588, 'skill_bonus': None},
 'ArMatrix B-Amplifier 33P (L)': {'decay': 0.528, 'ammo_burn': 693, 'skill_bonus': None},
 'ArMatrix B-Amplifier 37P (L)': {'decay': 0.592, 'ammo_burn': 777, 'skill_bonus': None},
 'ArMatrix B-Amplifier 42P (L)': {'decay': 0.672, 'ammo_burn': 882, 'skill_bonus': None},
 'ArMatrix B-Amplifier 45P (L)': {'decay': 0.72, 'ammo_burn': 945, 'skill_bonus': None},
 'ArMatrix B-Amplifier 4P (L)': {'decay': 0.064, 'ammo_burn': 84, 'skill_bonus': None},
 'ArMatrix B-Amplifier 50P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 55P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 60P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 65P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 6P (L)': {'decay': 0.096, 'ammo_burn': 126, 'skill_bonus': None},
 'ArMatrix B-Amplifier 70P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 75P (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix B-Amplifier 8P (L)': {'decay': 0.128, 'ammo_burn': 168, 'skill_bonus': None},
 'ArMatrix EXPA-100 (L)': {'decay': 1, 'ammo_burn': 1800, 'skill_bonus': None},
 'ArMatrix EXPA-125 (L)': {'decay': 1.25, 'ammo_burn': 2250, 'skill_bonus': None},
 'ArMatrix EXPA-150 (L)': {'decay': 1.5, 'ammo_burn': 0, 'skill_bonus': None},
 'ArMatrix EXPA-175 (L)': {'decay': 1.75, 'ammo_burn': 3150, 'skill_bonus': None},
 'ArMatrix EXPA-200 (L)': {'decay': 2, 'ammo_burn': 3600, 'skill_bonus': None},
 'ArMatrix EXPA-50 (L)': {'decay': 0.5, 'ammo_burn': 900, 'skill_bonus': None},
 'ArMatrix EXPA-75 (L)': {'decay': 0.75, 'ammo_burn': 1350, 'skill_bonus': None},
 'ArMatrix L-Amplifier 10B (L)': {'decay': 0.16, 'ammo_burn': 210, 'skill_bonus': None},
 'ArMatrix L-Amplifier 13B (L)': {'decay': 0.208, 'ammo_burn': 273, 'skill_bonus': None},
 'ArMatrix L-Amplifier 17B (L)': {'decay': 0.272, 'ammo_burn': 357, 'skill_bonus': None},
 'ArMatrix L-Amplifier 20B (L)': {'decay': 0.32, 'ammo_burn': 420, 'skill_bonus': None},
 'ArMatrix L-Amplifier 23B (L)': {'decay': 0.368, 'ammo_burn': 483, 'skill_bonus': None},
 'ArMatrix L-Amplifier 25B (L)': {'decay': 0.4, 'ammo_burn': 525, 'skill_bonus': None},
 'ArMatrix L-Amplifier 28B (L)': {'decay': 0.448, 'ammo_burn': 588, 'skill_bonus': None},
 'ArMatrix L-Amplifier 33B (L)': {'decay': 0.528, 'ammo_burn': 693, 'skill_bonus': None},
 'ArMatrix L-Amplifier 37B (L)': {'decay': 0.592, 'ammo_burn': 777, 'skill_bonus': None},
 'ArMatrix L-Amplifier 42B (L)': {'decay': 0.672, 'ammo_burn': 882, 'skill_bonus': None},
 'ArMatrix L-Amplifier 45B (L)': {'decay': 0.72, 'ammo_burn': 945, 'skill_bonus': None},
 'ArMatrix L-Amplifier 4B (L)': {'decay': 0.064, 'ammo_burn': 84, 'skill_bonus': None},
 'ArMatrix L-Amplifier 50B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 55B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 60B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 65B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 6B (L)': {'decay': 0.096, 'ammo_burn': 126, 'skill_bonus': None},
 'ArMatrix L-Amplifier 70B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 75B (L)': {'decay': 0.787, 'ammo_burn': 1032, 'skill_bonus': None},
 'ArMatrix L-Amplifier 8B (L)': {'decay': 0.128, 'ammo_burn': 168, 'skill_bonus': None},
 'Block Rocker BLP Mk I (L)': {'decay': 3.297, 'ammo_burn': 0, 'skill_bonus': None},
 'Block Rocker BLP Mk II (L)': {'decay': 6.865, 'ammo_burn': 0, 'skill_bonus': None},
 'Boom AAC (L)': {'decay': 1.831, 'ammo_burn': 500, 'skill_bonus': None},
 'Boom ACC (L)': {'decay': 1.437, 'ammo_burn': 100, 'skill_bonus': None},
 'Boom BBC (L)': {'decay': 4.751, 'ammo_burn': 1200, 'skill_bonus': None},
 'Boom BCC (L)': {'decay': 1.847, 'ammo_burn': 300, 'skill_bonus': None},
 'Boom CCC (L)': {'decay': 0.969, 'ammo_burn': 0, 'skill_bonus': None},
 'Bull Tac10 (L)': {'decay': 0.477, 'ammo_burn': 0, 'skill_bonus': None},
 'Bull Tac20 (L)': {'decay': 1.195, 'ammo_burn': 0, 'skill_bonus': None},
 'Bull Tac25 (L)': {'decay': 0.929, 'ammo_burn': 100, 'skill_bonus': None},
 'Bull Tac30 (L)': {'decay': 1.139, 'ammo_burn': 200, 'skill_bonus': None},
 'Bull Tac40 (L)': {'decay': 1.093, 'ammo_burn': 300, 'skill_bonus': None},
 'Bull Tac50 (L)': {'decay': 1.311, 'ammo_burn': 400, 'skill_bonus': None},
 'Bull Tac60 (L)': {'decay': 1.779, 'ammo_burn': 400, 'skill_bonus': None},
 'Bull Tac70 (L)': {'decay': 1.975, 'ammo_burn': 600, 'skill_bonus': None},
 'Bull Tac80 (L)': {'decay': 2.451, 'ammo_burn': 700, 'skill_bonus': None},
 'Bull TacElite (L)': {'decay': 3.207, 'ammo_burn': 900, 'skill_bonus': None},
 'Bust-A-BLP Mk I (L)': {'decay': None, 'ammo_burn': None, 'skill_bonus': None},
 'Bust-A-BLP Mk II (L)': {'decay': None, 'ammo_burn': 0, 'skill_bonus': None},
 'CDF BLP Power Amp 1 (L)': {'decay': 0.22, 'ammo_burn': 409, 'skill_bonus': None},
 'CDF BLP Power Amp 2 (L)': {'decay': 0.37, 'ammo_burn': 632, 'skill_bonus': None},
 'CDF BLP Power Amp 3 (L)': {'decay': 0.44, 'ammo_burn': 810, 'skill_bonus': None},
 'CDF BLP Power Amp 4 (L)': {'decay': 0.74, 'ammo_burn': 1400, 'skill_bonus': None},
 'CDF Laser Power Amp 1 (L)': {'decay': 0.26, 'ammo_burn': 402, 'skill_bonus': None},
 'CDF Laser Power Amp 2 (L)': {'decay': 0.35, 'ammo_burn': 530, 'skill_bonus': None},
 'CDF Laser Power Amp 3 (L)': {'decay': 0.52, 'ammo_burn': 880, 'skill_bonus': None},
 'CDF Laser Power Amp 4 (L)': {'decay': 0.96, 'ammo_burn': 1722, 'skill_bonus': None},
 'Chahen BLP V1 (L)': {'decay': 0.66, 'ammo_burn': None, 'skill_bonus': None},
 'Chahen BLP V2 (L)': {'decay': 1.25, 'ammo_burn': 68, 'skill_bonus': None},
 'Chahen BLP V3 (L)': {'decay': None, 'ammo_burn': 110, 'skill_bonus': None},
 'DSEC BLP Amp v1 (L)': {'decay': 1.18, 'ammo_burn': 351, 'skill_bonus': None},
 'DSEC BLP Amp v2 (L)': {'decay': 3.1, 'ammo_burn': 524, 'skill_bonus': None},
 'DSEC Laser Amp v1 (L)': {'decay': 1.02, 'ammo_burn': 312, 'skill_bonus': None},
 'DSEC Laser Amp v2 (L)': {'decay': 2.7, 'ammo_burn': 483, 'skill_bonus': None},
 'E-Amp 11': {'decay': 0.711, 'ammo_burn': 100, 'skill_bonus': None},
 'E-Amp 12': {'decay': 1.555, 'ammo_burn': 100, 'skill_bonus': None},
 'E-Amp 13': {'decay': 2.943, 'ammo_burn': 100, 'skill_bonus': None},
 'E-Amp 14': {'decay': 4.311, 'ammo_burn': 100, 'skill_bonus': None},
 'E-Amp 15': {'decay': 5.633, 'ammo_burn': 100, 'skill_bonus': None},
 'Enkidd Black Widow (L)': {'decay': 1.6, 'ammo_burn': 200, 'skill_bonus': None},
 'Enkidd Brown Recluse (L)': {'decay': 1.8, 'ammo_burn': 300, 'skill_bonus': None},
 'Enkidd Camel Spider (L)': {'decay': 1.4, 'ammo_burn': 100, 'skill_bonus': None},
 'Enkidd Red-Back (L)': {'decay': 1.2, 'ammo_burn': 0, 'skill_bonus': None},
 'Exceptional Mayhem MC-Matrix Mk.2 (L)': {'decay': 0.025, 'ammo_burn': None, 'skill_bonus': None},
 'Fi/Ra/Co Angst': {'decay': 1.897, 'ammo_burn': 200, 'skill_bonus': None},
 'Fi/Ra/Co Beast': {'decay': 2.366, 'ammo_burn': 200, 'skill_bonus': None},
 'Fi/Ra/Co Beast, SGA Edition': {'decay': 2.826, 'ammo_burn': 200, 'skill_bonus': None},
 'Fi/Ra/Co Cause': {'decay': 4.522, 'ammo_burn': 200, 'skill_bonus': None},
 'Fi/Ra/Co Cause, Adjusted': {'decay': 4.102, 'ammo_burn': 245, 'skill_bonus': None},
 'Fi/Ra/Co Cause, Improved': {'decay': 3.88, 'ammo_burn': 276, 'skill_bonus': None},
 'Fi/Ra/Co Cause, Modified': {'decay': 3.83, 'ammo_burn': 292, 'skill_bonus': None},
 'Fi/Ra/Co Dante': {'decay': 4, 'ammo_burn': 300, 'skill_bonus': None},
 'Fi/Ra/Co Evil': {'decay': 5.95, 'ammo_burn': 300, 'skill_bonus': None},
 'Fi/Ra/Co Evil, Adjusted': {'decay': 5.95, 'ammo_burn': 320, 'skill_bonus': None},
 'Fi/Ra/Co Evil, Augmented': {'decay': 0.6, 'ammo_burn': 954, 'skill_bonus': None},
 'Fi/Ra/Co Evil, Improved': {'decay': 5.95, 'ammo_burn': 354, 'skill_bonus': None},
 'Fi/Ra/Co Evil, Modified': {'decay': 5.95, 'ammo_burn': 386, 'skill_bonus': None},
 'Hotfoot 10 (L)': {'decay': 0.465, 'ammo_burn': 190, 'skill_bonus': None},
 'Hotfoot 15 (L)': {'decay': 0.79, 'ammo_burn': 325, 'skill_bonus': None},
 'Hotfoot 20 (L)': {'decay': 1.066, 'ammo_burn': 465, 'skill_bonus': None},
 'Hotfoot 25 (L)': {'decay': 1.261, 'ammo_burn': 565, 'skill_bonus': None},
 'Hotfoot 30 (L)': {'decay': 1.589, 'ammo_burn': 700, 'skill_bonus': None},
 'Hotfoot 35 (L)': {'decay': 1.826, 'ammo_burn': 820, 'skill_bonus': None},
 'Hotfoot 40 (L)': {'decay': 2.077, 'ammo_burn': 915, 'skill_bonus': None},
 'Hotfoot 45 (L)': {'decay': 2.351, 'ammo_burn': 1055, 'skill_bonus': None},
 'Hotfoot 5 (L)': {'decay': 0.182, 'ammo_burn': 75, 'skill_bonus': None},
 'Hotfoot 50 (L)': {'decay': 2.509, 'ammo_burn': 1135, 'skill_bonus': None},
 'Kismet Assistance Module 4 (L)': {'decay': 0.3, 'ammo_burn': 300, 'skill_bonus': None},
 'Kismet Damage Amplifier 3 (L)': {'decay': 0.031, 'ammo_burn': 587, 'skill_bonus': None},
 'Kismet Damage Amplifier 4 (L)': {'decay': 0.061, 'ammo_burn': 1159, 'skill_bonus': None},
 'Kismet Decay Deflector 4 (L)': {'decay': 0.5, 'ammo_burn': 1000, 'skill_bonus': None},
 'Kismet Premium Laser Booster 1 (L)': {'decay': 0.05, 'ammo_burn': 475, 'skill_bonus': None},
 'Kismet Premium Laser Booster 2 (L)': {'decay': 0.19, 'ammo_burn': 1805, 'skill_bonus': None},
 'Kismet Premium Laser Booster 3 (L)': {'decay': 0.4, 'ammo_burn': 3800, 'skill_bonus': None},
 'Loughlin HyperEdge M-Amp 1 (L)': {'decay': 0.889, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin HyperEdge M-Amp 2 (L)': {'decay': 1.778, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin Master M-Amp 1 (L)': {'decay': 0.476, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin Master M-Amp 2 (L)': {'decay': 0.952, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin Master M-Amp 4 (L)': {'decay': 1.904, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin NanoRep M-Amp 1 (L)': {'decay': 0.25, 'ammo_burn': 0, 'skill_bonus': None},
 'Loughlin NanoRep M-Amp 2 (L)': {'decay': 0.25, 'ammo_burn': 0, 'skill_bonus': None},
 'Low Rider BLP Amp Mk I (L)': {'decay': 4.643, 'ammo_burn': 0, 'skill_bonus': None},
 'Low Rider BLP Amp Mk II (L)': {'decay': 10.1, 'ammo_burn': 0, 'skill_bonus': None},
 'M-Matrix, TWEN Edition': {'decay': 0.025, 'ammo_burn': 0, 'skill_bonus': None},
 'Marshall Laser Amp Mk I (L)': {'decay': 2.331, 'ammo_burn': 0, 'skill_bonus': None},
 'Marshall Laser Amp Mk II (L)': {'decay': 3.943, 'ammo_burn': None, 'skill_bonus': None},
 'Mayhem B-Amplifier 110P (L)': {'decay': 0.787, 'ammo_burn': 1600, 'skill_bonus': None},
 'Mayhem B-Amplifier Alpha (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem B-Amplifier Beta (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem B-Amplifier Delta (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem B-Amplifier Gamma (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem Kinetic Amplifier 1': {'decay': 1.2, 'ammo_burn': 1080, 'skill_bonus': None},
 'Mayhem Kinetic Amplifier 2': {'decay': 1.4, 'ammo_burn': 1260, 'skill_bonus': None},
 'Mayhem Kinetic Amplifier 3': {'decay': 1.6, 'ammo_burn': 1440, 'skill_bonus': None},
 'Mayhem Kinetic Amplifier 4': {'decay': 1.8, 'ammo_burn': 1620, 'skill_bonus': None},
 'Mayhem Kinetic Amplifier 5': {'decay': 2, 'ammo_burn': 1800, 'skill_bonus': None},
 'Mayhem L-Amplifier Alpha (L)': {'decay': 0.019, 'ammo_burn': 898, 'skill_bonus': None},
 'Mayhem L-Amplifier Beta (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem L-Amplifier Delta (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem L-Amplifier Gamma (L)': {'decay': 0.019, 'ammo_burn': 998, 'skill_bonus': None},
 'Mayhem M-Matrix Alpha (L)': {'decay': 0.019, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem M-Matrix Beta (L)': {'decay': 0.019, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem M-Matrix Delta (L)': {'decay': 0.019, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem M-Matrix Gamma (L)': {'decay': 0.019, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem MC-Matrix Mk.1': {'decay': 0.025, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem MF-Amplifier Alpha (L)': {'decay': 0.019, 'ammo_burn': 898, 'skill_bonus': None},
 'Mayhem MF-Amplifier Beta (L)': {'decay': 0.019, 'ammo_burn': 898, 'skill_bonus': None},
 'Mayhem MF-Amplifier Delta (L)': {'decay': 0.019, 'ammo_burn': 898, 'skill_bonus': None},
 'Mayhem MF-Amplifier Gamma (L)': {'decay': 0.019, 'ammo_burn': 898, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 1': {'decay': 12, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 2': {'decay': 14, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 3': {'decay': 16, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 4': {'decay': 18, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 5': {'decay': 20, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 6': {'decay': 22.105, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier 7': {'decay': 24.21, 'ammo_burn': 0, 'skill_bonus': None},
 'Mayhem Trauma Amplifier E-137 (L)': {'decay': 25, 'ammo_burn': 0, 'skill_bonus': None},
 'MC-Matrix Mk. 1, TWEN Edition': {'decay': 0.0257, 'ammo_burn': 0, 'skill_bonus': None},
 'MC-Matrix Mk. 2, TWEN Edition': {'decay': 0.03, 'ammo_burn': 0, 'skill_bonus': None},
 'MC-Matrix Mk. 3, TWEN Edition': {'decay': 0.033, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Bimodal Amplifier 1 (L)': {'decay': 0.476, 'ammo_burn': None, 'skill_bonus': None},
 'Melee Bimodal Amplifier 2 (L)': {'decay': 0.952, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Bimodal Amplifier 3 (L)': {'decay': 1.428, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Durability Amplifier 1 (L)': {'decay': 0.25, 'ammo_burn': None, 'skill_bonus': None},
 'Melee Durability Amplifier 2 (L)': {'decay': 0.25, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Durability Amplifier 3 (L)': {'decay': 0.25, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Durability Amplifier 92 (L)': {'decay': 0.99, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Durability Amplifier 94 (L)': {'decay': 0.99, 'ammo_burn': None, 'skill_bonus': None},
 'Melee Durability Amplifier 96 (L)': {'decay': 0.99, 'ammo_burn': None, 'skill_bonus': None},
 'Melee Trauma Amplifier 1': {'decay': 0.889, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 1 (L)': {'decay': 0.889, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 10': {'decay': 9.779, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 10, FEN Edition': {'decay': 10.668, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 2': {'decay': 1.778, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 2 (L)': {'decay': 1.778, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 2, Adjusted': {'decay': 1.768, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 2, FEN Edition': {'decay': 2.667, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 3': {'decay': 3.556, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 3 (L)': {'decay': 3.556, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 4': {'decay': 4.445, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 5': {'decay': 5.334, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 6': {'decay': 6.223, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 6, Improved': {'decay': 6.108, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 7': {'decay': 7.112, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 7, TWEN Edition': {'decay': 7.112, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 8': {'decay': 8.001, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 8, Modified': {'decay': 7.766, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 9': {'decay': 8.89, 'ammo_burn': 0, 'skill_bonus': None},
 'Melee Trauma Amplifier 9, TWEN Edition': {'decay': 9.34, 'ammo_burn': 0, 'skill_bonus': None},
 'Mestawy Melee V1 (L)': {'decay': None, 'ammo_burn': 0, 'skill_bonus': None},
 'Muzwed Energy V1 (L)': {'decay': 0.8, 'ammo_burn': 40, 'skill_bonus': None},
 'Muzwed Energy V2 (L)': {'decay': None, 'ammo_burn': 110, 'skill_bonus': None},
 'Muzwed Energy V3 (L)': {'decay': None, 'ammo_burn': 166, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 1': {'decay': 0.042, 'ammo_burn': 42, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 1 (L)': {'decay': 0.045, 'ammo_burn': 39, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 2': {'decay': 0.083, 'ammo_burn': 84, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 2 (L)': {'decay': 0.088, 'ammo_burn': 78, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 3': {'decay': 0.152, 'ammo_burn': 169, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 3 (L)': {'decay': 0.164, 'ammo_burn': 157, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 4': {'decay': 0.23, 'ammo_burn': 253, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 4 (L)': {'decay': 0.245, 'ammo_burn': 235, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 5': {'decay': 0.333, 'ammo_burn': 380, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 5 (L)': {'decay': 0.36, 'ammo_burn': 353, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 6': {'decay': 0.5, 'ammo_burn': 570, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 6 (L)': {'decay': 0.533, 'ammo_burn': 530, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 7': {'decay': 0.67, 'ammo_burn': 758, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 7 (L)': {'decay': 0.71, 'ammo_burn': 706, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier 7, FEN Edition': {'decay': 0.744, 'ammo_burn': 842, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier Mk.1, TWEN Edition': {'decay': 0.67, 'ammo_burn': 850, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier Mk.2, TWEN Edition': {'decay': 0.8, 'ammo_burn': 1142, 'skill_bonus': None},
 'NeoPsion Kinetic Amplifier Mk.3, TWEN Edition': {'decay': 0.9, 'ammo_burn': 1742, 'skill_bonus': None},
 'Omegaton A101': {'decay': 0.652, 'ammo_burn': 0, 'skill_bonus': None},
 'Omegaton A102': {'decay': 0.521, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A103': {'decay': 1.606, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A104': {'decay': 2.039, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A104, Ancient': {'decay': 3.012, 'ammo_burn': 0, 'skill_bonus': None},
 'Omegaton A104, SGA Edition': {'decay': 2.267, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A105': {'decay': 2.47, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A105 Hypercharged': {'decay': 2.47, 'ammo_burn': 228, 'skill_bonus': None},
 'Omegaton A105 Overcharged': {'decay': 2.47, 'ammo_burn': 175, 'skill_bonus': None},
 'Omegaton A105, Adjusted': {'decay': 2.476, 'ammo_burn': 121, 'skill_bonus': None},
 'Omegaton A105, Improved': {'decay': 2.473, 'ammo_burn': 143, 'skill_bonus': None},
 'Omegaton A105, Modified': {'decay': 0.473, 'ammo_burn': 362, 'skill_bonus': None},
 'Omegaton A106': {'decay': 2.902, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A201': {'decay': 0.521, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A202': {'decay': 1.164, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A203': {'decay': 2.243, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A204': {'decay': 3.31, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A204 Hypercharged': {'decay': 3.315, 'ammo_burn': 374, 'skill_bonus': None},
 'Omegaton A204 Overcharged': {'decay': 3.31, 'ammo_burn': 242, 'skill_bonus': None},
 'Omegaton A204, Adjusted': {'decay': 3.316, 'ammo_burn': 121, 'skill_bonus': None},
 'Omegaton A204, Improved': {'decay': 3.311, 'ammo_burn': 143, 'skill_bonus': None},
 'Omegaton A204, Modified': {'decay': 0.5, 'ammo_burn': 444, 'skill_bonus': None},
 'Omegaton A204, SGA Edition': {'decay': 3.793, 'ammo_burn': 100, 'skill_bonus': None},
 'Omegaton A204, Supercharged': {'decay': 0.5, 'ammo_burn': 788, 'skill_bonus': None},
 'Omegaton Amplifier, Modified': {'decay': 7.68, 'ammo_burn': 400, 'skill_bonus': None},
 'Omegaton B101 (L)': {'decay': 0.002, 'ammo_burn': 23, 'skill_bonus': None},
 'Omegaton Decay Absorber 3 (L)': {'decay': 0.6, 'ammo_burn': 85, 'skill_bonus': None},
 'Rage 10 (L)': {'decay': 0.467, 'ammo_burn': 165, 'skill_bonus': None},
 'Rage 15 (L)': {'decay': 0.781, 'ammo_burn': 300, 'skill_bonus': None},
 'Rage 20': {'decay': 1.063, 'ammo_burn': 415, 'skill_bonus': None},
 'Rage 20 (L)': {'decay': 1.063, 'ammo_burn': 415, 'skill_bonus': None},
 'Rage 25': {'decay': 1.255, 'ammo_burn': 515, 'skill_bonus': None},
 'Rage 25 (L)': {'decay': 1.255, 'ammo_burn': 515, 'skill_bonus': None},
 'Rage 30 (L)': {'decay': 1.459, 'ammo_burn': 590, 'skill_bonus': None},
 'Rage 35': {'decay': 1.574, 'ammo_burn': 650, 'skill_bonus': None},
 'Rage 35 (L)': {'decay': 1.574, 'ammo_burn': 650, 'skill_bonus': None},
 'Rage 40 (L)': {'decay': 1.778, 'ammo_burn': 725, 'skill_bonus': None},
 'Rage 45 (L)': {'decay': 2.098, 'ammo_burn': 860, 'skill_bonus': None},
 'Rage 5 (L)': {'decay': 0.226, 'ammo_burn': 70, 'skill_bonus': None},
 'Rage 50 (L)': {'decay': 2.302, 'ammo_burn': 935, 'skill_bonus': None},
 'RapMan (L)': {'decay': 1.831, 'ammo_burn': 500, 'skill_bonus': None},
 'Rapper (L)': {'decay': 1.437, 'ammo_burn': 100, 'skill_bonus': None},
 'Rapper Snapper (L)': {'decay': 1.843, 'ammo_burn': 300, 'skill_bonus': None},
 'RapSTAR (L)': {'decay': 2.757, 'ammo_burn': 800, 'skill_bonus': None},
 'RDI Binary Amplifier (L)': {'decay': 0.02, 'ammo_burn': 700, 'skill_bonus': None},
 'RDI Energy Amplifier Alpha (L)': {'decay': 0.01, 'ammo_burn': 350, 'skill_bonus': None},
 'RDI Energy Amplifier Beta (L)': {'decay': 0.02, 'ammo_burn': 700, 'skill_bonus': None},
 'RDI Energy Amplifier Gamma': {'decay': 0.02, 'ammo_burn': 1100, 'skill_bonus': None},
 'RDI Energy Amplifier Gamma (L)': {'decay': 0.02, 'ammo_burn': 1000, 'skill_bonus': None},
 'RDI Trauma Amplifier E2 (L)': {'decay': 0.25, 'ammo_burn': 0, 'skill_bonus': None},
 'Road-Monkey Laser Amp Mk I (L)': {'decay': 0.478, 'ammo_burn': 0, 'skill_bonus': None},
 'Road-Monkey Laser Amp Mk IV (L)': {'decay': 3, 'ammo_burn': 0, 'skill_bonus': None},
 'Roadie BLP Mk I (L)': {'decay': 0.477, 'ammo_burn': 0, 'skill_bonus': None},
 'Roadie BLP Mk II (L)': {'decay': 1.194, 'ammo_burn': 0, 'skill_bonus': None},
 'Rookie Laser Amp (L)': {'decay': 0.046, 'ammo_burn': 20, 'skill_bonus': None},
 'Shack-A-Lacka Laser Amp Mk I (L)': {'decay': 6.5, 'ammo_burn': 0, 'skill_bonus': None},
 'Shack-A-Lacka Laser Amp Mk II (L)': {'decay': 2.34, 'ammo_burn': 0, 'skill_bonus': None},
 'Shear Pro600 (L)': {'decay': 1.975, 'ammo_burn': 600, 'skill_bonus': None},
 'Shear Pro700 (L)': {'decay': 2.451, 'ammo_burn': 700, 'skill_bonus': None},
 'Shear Pro900 (L)': {'decay': 3.207, 'ammo_burn': 900, 'skill_bonus': None},
 'Shear ProM (L)': {'decay': 3.773, 'ammo_burn': 1000, 'skill_bonus': None},
 'Shear ProMC (L)': {'decay': 4.847, 'ammo_burn': 1400, 'skill_bonus': None},
 'Shear XR40 (L)': {'decay': 0.478, 'ammo_burn': 0, 'skill_bonus': None},
 'Shear XR50 (L)': {'decay': 1.195, 'ammo_burn': 0, 'skill_bonus': None},
 'Shear XR55 (L)': {'decay': 0.931, 'ammo_burn': 100, 'skill_bonus': None},
 'Shear XR60 (L)': {'decay': 1.139, 'ammo_burn': 200, 'skill_bonus': None},
 'Shear XR70 (L)': {'decay': 1.093, 'ammo_burn': 300, 'skill_bonus': None},
 'Shear XR80 (L)': {'decay': 1.311, 'ammo_burn': 400, 'skill_bonus': None},
 'Shear XR90 (L)': {'decay': 1.779, 'ammo_burn': 400, 'skill_bonus': None},
 'Stable Turrelion Amp': {'decay': 2.2, 'ammo_burn': 2000, 'skill_bonus': None},
 'T-Rap (L)': {'decay': 0.969, 'ammo_burn': 0, 'skill_bonus': None},
 'Teenie Weenie Laser Amp Mk I (L)': {'decay': 0.692, 'ammo_burn': 0, 'skill_bonus': None},
 'Teenie Weenie Laser Amp Mk II (L)': {'decay': 1.621, 'ammo_burn': 0, 'skill_bonus': None},
 'Xent Tech Light Amplification Crenshaw (L)': {'decay': 1.8, 'ammo_burn': 300, 'skill_bonus': None},
 'Xent Tech Light Amplification Sunset (L)': {'decay': 1.4, 'ammo_burn': 100, 'skill_bonus': None},
 'Xent Tech Light Amplification Vine (L)': {'decay': 1.2, 'ammo_burn': 0, 'skill_bonus': None},
 'Xent Tech Light Amplification Wilshire (L)': {'decay': 1.6, 'ammo_burn': 200, 'skill_bonus': None},
 "Zorra's Blessed Laser Amp (L)": {'decay': 0.15, 'ammo_burn': 1707, 'skill_bonus': 10},
 'ZX Sinkadus': {'decay': 0.032, 'ammo_burn': 40, 'skill_bonus': None}}
