# Auto-generated from Entropia Nexus atachements.json.
# This file is hardcoded and does not call the internet.
#
# Values:
#   decay       - item decay as exported by Entropia Nexus
#   ammo_burn   - always 0 for attachments
#   skill_bonus - attachment SkillBonus value; None if missing

ATTACHMENTS = {'Abrer Laser Sight': {'decay': 0.046, 'ammo_burn': 0, 'skill_bonus': 0.9},
 'Alekz Precision Scope': {'decay': 0.029, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'ArMatrix Laser Sight Mk.1, TWEN Edition': {'decay': 0.015, 'ammo_burn': 0, 'skill_bonus': 2},
 'ArMatrix Laser Sight Mk.2, TWEN Edition': {'decay': 0.015, 'ammo_burn': 0, 'skill_bonus': 2},
 'ArMatrix Laser Sight Mk.3, TWEN Edition': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 2},
 'ArMatrix Precision Scope Mk.1, TWEN Edition': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1},
 'ArMatrix Precision Scope Mk.2, TWEN Edition': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1},
 'ArMatrix Precision Scope Mk.3, TWEN Edition': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1},
 'Beacin Laser Sight': {'decay': 0.069, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Bjornir Precision Scope': {'decay': 0.039, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Bullseye 1': {'decay': 0.04, 'ammo_burn': 0, 'skill_bonus': 1},
 'Bullseye 2': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.1},
 'Bullseye 3': {'decay': 0.06, 'ammo_burn': 0, 'skill_bonus': 1.2},
 'Bullseye 4': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Bullseye 5': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Bullseye 6': {'decay': 0.09, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'Bullseye 7': {'decay': 0.1, 'ammo_burn': 0, 'skill_bonus': 1.6},
 'Bullseye 8': {'decay': 0.11, 'ammo_burn': 0, 'skill_bonus': 1.7},
 'Bullseye I (L)': {'decay': 0.04, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Bullseye II (L)': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Bullseye III (L)': {'decay': 0.06, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'Bullseye IV (L)': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 1.6},
 'Bullseye V (L)': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1.7},
 'Bullseye VI (L)': {'decay': 0.09, 'ammo_burn': 0, 'skill_bonus': 1.8},
 'Bullseye VII (L)': {'decay': 0.1, 'ammo_burn': 0, 'skill_bonus': 1.9},
 'Bullseye VIII (L)': {'decay': 0.11, 'ammo_burn': 0, 'skill_bonus': 2},
 'Castar Laser Sight': {'decay': 0.088, 'ammo_burn': 0, 'skill_bonus': 1.8},
 'Cinclar Precision Scope': {'decay': 0.042, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Dacascos Precision Scope': {'decay': 0.051, 'ammo_burn': 0, 'skill_bonus': 1},
 'Dynera Laser Sight': {'decay': 0.096, 'ammo_burn': 0, 'skill_bonus': 1.9},
 'Ecivox Laser Sight': {'decay': 0.066, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Elkarr Precision Scope': {'decay': 0.059, 'ammo_burn': 0, 'skill_bonus': 1.2},
 'Enkidd Dismalites (L)': {'decay': 0.1, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'Exceptional Mayhem Laser Sight Mk.2 (L)': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 2},
 'Exceptional Mayhem Precision Scope Mk.2 (L)': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1},
 'Flexur Precision Scope': {'decay': 0.066, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Framur Laser Sight': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1.6},
 'Gargul Laser Sight': {'decay': 0.09, 'ammo_burn': 0, 'skill_bonus': 1.8},
 'Grender Precision Scope': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 0.4},
 'Hanzor Precision Scope': {'decay': 0.071, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Hawk 1k (L)': {'decay': 0.036, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Hawk 2k (L)': {'decay': 0.04, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Hawk 3k (L)': {'decay': 0.042, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Headshot 1': {'decay': 0.023, 'ammo_burn': 0, 'skill_bonus': 1.1},
 'Headshot 2': {'decay': 0.032, 'ammo_burn': 0, 'skill_bonus': 1.2},
 'Headshot 3': {'decay': 0.041, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Headshot 4': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Headshot I (L)': {'decay': 0.023, 'ammo_burn': 0, 'skill_bonus': 1.2},
 'Headshot II (L)': {'decay': 0.032, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'Headshot III (L)': {'decay': 0.041, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Headshot IV (L)': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'Hunnir Laser Sight': {'decay': 0.098, 'ammo_burn': 0, 'skill_bonus': 2},
 'I.C.U Laser Sight Mk I': {'decay': 0.03, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Ignaritz Laser Sight': {'decay': 0.109, 'ammo_burn': 0, 'skill_bonus': 2.2},
 'Ikamar Precision Scope': {'decay': 0.082, 'ammo_burn': 0, 'skill_bonus': 1.6},
 'Jakth Laser Sight': {'decay': 0.126, 'ammo_burn': 0, 'skill_bonus': 2.5},
 'Jzar Precision Scope': {'decay': 0.088, 'ammo_burn': 0, 'skill_bonus': 1.8},
 'Longreach 1': {'decay': 0.058, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Longreach 2': {'decay': 0.066, 'ammo_burn': 0, 'skill_bonus': 0.7},
 'Longreach 3': {'decay': 0.075, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Longreach 4': {'decay': 0.083, 'ammo_burn': 0, 'skill_bonus': 0.9},
 'Longreach I (L)': {'decay': 0.058, 'ammo_burn': 0, 'skill_bonus': 0.7},
 'Longreach II (L)': {'decay': 0.066, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Longreach III (L)': {'decay': 0.075, 'ammo_burn': 0, 'skill_bonus': 0.9},
 'Longreach IV (L)': {'decay': 0.083, 'ammo_burn': 0, 'skill_bonus': 1},
 'Lucky Laser Sight Mk I': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Lucky Laser Sight Mk II': {'decay': 0.03, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Mayhem Laser Sight Mk.1': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 2},
 'Mayhem Precision Scope Mk.1': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1},
 'Omegaton Laser Sight Mk. 1': {'decay': 0.098, 'ammo_burn': 0, 'skill_bonus': 2},
 'Omegaton Laser Sight Mk. 2': {'decay': 0.1, 'ammo_burn': 0, 'skill_bonus': 2},
 'Omegaton Ranger Scope Mk. 1': {'decay': 0.071, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Omegaton Ranger Scope Mk. 2': {'decay': 0.071, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'Prototype Mounted Flashlight Smuggler': {'decay': 0.001, 'ammo_burn': 0, 'skill_bonus': None},
 'S & B Mounted Light P1 (L)': {'decay': 0.04, 'ammo_burn': 0, 'skill_bonus': 1.3},
 'S & B Mounted Light P2 (L)': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.4},
 'S & B Mounted Light R1 (L)': {'decay': 0.09, 'ammo_burn': 0, 'skill_bonus': 1.8},
 'S & B Mounted Light R2 (L)': {'decay': 0.06, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'S & B Mounted Light R3 (L)': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 1.6},
 'S & B Mounted Light R4 (L)': {'decay': 0.08, 'ammo_burn': 0, 'skill_bonus': 1.7},
 'Salafa Laser Sight MK 1 (L)': {'decay': 0.04, 'ammo_burn': 0, 'skill_bonus': 1},
 'Salafa Laser Sight MK 2 (L)': {'decay': 0.05, 'ammo_burn': 0, 'skill_bonus': 1.5},
 'Salafa Laser Sight MK 3 (L)': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 2.5},
 'Seizzt Laser Sight 2000L': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 0.4},
 'Seizzt Laser Sight 2000L+': {'decay': 0.017, 'ammo_burn': 0, 'skill_bonus': 0.3},
 'Seizzt Ranger Scope 1800RS': {'decay': 0.021, 'ammo_burn': 0, 'skill_bonus': 0.4},
 'Seizzt Ranger Scope 1850RS': {'decay': 0.023, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Seizzt Ranger Scope 1900RS': {'decay': 0.026, 'ammo_burn': 0, 'skill_bonus': 0.5},
 'Seizzt Ranger Scope 1950RS': {'decay': 0.028, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Seizzt Ranger Scope 2500RS': {'decay': 0.032, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Seizzt Ranger Scope 3500RS': {'decay': 0.037, 'ammo_burn': 0, 'skill_bonus': 0.7},
 'Seizzt Ranger Scope 4000RS': {'decay': 0.038, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Sight of Cthylla': {'decay': 0.07, 'ammo_burn': 0, 'skill_bonus': 2.5},
 'Stable Turrelion Scope': {'decay': 0.075, 'ammo_burn': 0, 'skill_bonus': 0.9},
 'Stable Turrelion Sight': {'decay': 0.075, 'ammo_burn': 0, 'skill_bonus': 1},
 'Sweet Scope Mk I': {'decay': 0.029, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Sweet Scope Mk II': {'decay': 0.039, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Sweet Scope Mk III': {'decay': 0.042, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'Terrus Laser Sight SE600': {'decay': 0.03, 'ammo_burn': 0, 'skill_bonus': 0.6},
 'Terrus Laser Sight SE700': {'decay': 0.036, 'ammo_burn': 0, 'skill_bonus': 0.7},
 'Terrus Laser Sight SE800': {'decay': 0.037, 'ammo_burn': 0, 'skill_bonus': 0.7},
 'Terrus Laser Sight SE900': {'decay': 0.039, 'ammo_burn': 0, 'skill_bonus': 0.8},
 'ZX Eagle Eye': {'decay': 0.014, 'ammo_burn': 0, 'skill_bonus': 0.2},
 'ZX R-Dod': {'decay': 0.02, 'ammo_burn': 0, 'skill_bonus': 0.4}}
